### ISSUE TITLE
ArenaManager error

### ISSUE THREAD

**Issue by sulubsquared** [jkorn2324/Practice#6]
[Server thread/CRITICAL]: TypeError: "file_exists() expects parameter 1 to be a valid path, null given" (EXCEPTION) in "plugins/Practice.phar/src/practice/arenas/ArenaManager" at line 30

**Comment by sshilohh** [comment]
ERROR: **[Server thread/CRITICAL]: TypeError: "file_exists() expects parameter 1 to be a valid path, null given" (EXCEPTION) in "plugins/Practice.phar/src/practice/arenas/ArenaManager" at line 30**

Fix: **Change main to old\practice\Practice in file _file plugin.yml_**

Maybe because your using, The Version That he's rewriting or the remake. Make Sure your change the main in plugin.yml to old\practice\Practice.
@Soupiia
